### ISSUE TITLE
Create sticky bottom navigation section

### ISSUE THREAD

**Issue by ckrina** [Lullabot/navigation#9]
### Description 

There is a section of the toolbar that will include the help link and the link to the user's profile page. This section of the toolbar will be sticky/always visible. Including these links in a sticky region will keep them easily accessible to site builders and content users.

### Activities in this ticket

Build the sticky region
When the toolbar scrolls, the sticky region should fall on top of the scrolling items (see screenshot for example)
When the toolbar is collapsed, it should collapse with the rest of the items
Both the help and the user menu links should stay links only for now - the current toolbar has menu items under the user section. For now, we want to focus only on the sticky region.

### Code example

https://codepen.io/robstinson/pen/bGwpNMV

![Image](https://user-images.githubusercontent.com/2225966/251190569-5009120c-2b68-4af2-a2d1-43fb80931e92.png)

**Comment by sveta1x** [comment]
1. Added sticky section to the toolbar
2. I didn't add any avatar image because for now I don't know how images will be implemented (avatar will be possible to change, as I understand). For now I just added a user-icon
3. For now I didn't add any styles like borders and shadows.

Please check my [PR]( https://github.com/Lullabot/navigation/pull/27)

and let me know if I should implement more styles and include an image

Thank you

**Comment by sveta1x** [comment]
Made changes according to the request in PR:

1. I added min-height for the toolbar as Cristina said but used media query for max-height 300px. I would also remove sticky position for this edge case and some margin-top as well. Then user could see the menu better. 

2. Added border and box-shadow for sticky part similar to the design.

needs to be checked again. THanks

**Comment by ckrina** [comment]
merged
